// packages/react/src/Dropdown.tsx
import * as React from 'react'

interface DropdownProps {
  name?: string
  disabled?: boolean
  onChange?(value: string): void
}

export const Dropdown: React.FC<DropdownProps> = ({ children, disabled, name, onChange }) => (
  <div className="mcss-selector" data-disabled={disabled ?? undefined}>
    <select
      className="mcss-select"
      name={name}
      disabled={disabled}
      onChange={(evt) => {
        if (onChange) {
          onChange(evt.target.value)
        }
      }}
    >
      {children}
    </select>
  </div>
)

export default Dropdown

// packages/svelte/src/Dropdown.svelte
<script lang="ts">
import { setContext, createEventDispatcher } from 'svelte'

const dispatch = createEventDispatcher()

export let name: string | undefined = undefined
export let disabled: boolean = false

const handleChange = (event: Event) => {
  dispatch('change', (event.target as HTMLSelectElement).value)
}
</script>

<div class="mcss-selector" data-disabled={disabled ? true : undefined}>
  <select class="mcss-select" {name} {disabled} on:change={handleChange}>
    <slot />
  </select>
</div>
