// packages/react/src/DropdownItem.tsx
import * as React from 'react'

export interface DropdownItemProps {
  selected?: boolean
  disabled?: boolean
  name?: string
  value?: string | number
}

export const DropdownItem: React.FC<DropdownItemProps> = ({
  children,
  disabled,
  selected,
  value,
}) => {
  return (
    <option className="mcss-option" value={value} disabled={disabled} selected={selected}>
      {children}
    </option>
  )
}

export default DropdownItem

// packages/svelte/src/DropdownItem.svelte
<script lang="ts">
import { createEventDispatcher } from 'svelte'

const dispatch = createEventDispatcher()

export let value: string | number | undefined = undefined
export let disabled: boolean = false
export let selected: boolean = false
</script>

<option class="mcss-option" {value} {disabled} {selected}>
  <slot />
</option>
