// packages/react/src/Radio.tsx
import * as React from 'react'
import { RadioGroupContext } from './RadioGroup'

export interface RadioProps {
  checked?: boolean
  disabled?: boolean
  name?: string
  value?: string | number
  onChange?(checked: boolean): void
}

export const Radio: React.FC<RadioProps> = ({
  children,
  disabled,
  checked,
  name,
  value,
  onChange,
}) => {
  return (
    <RadioGroupContext.Consumer>
      {({ name: providedName, onChange: providedOnChange }) => (
        <label className="mcss-radio-container">
          <input
            className="mcss-radio"
            type="radio"
            checked={checked}
            disabled={disabled}
            name={providedName ?? name}
            value={value}
            onChange={(evt) => {
              const isChecked = (evt.target as HTMLInputElement).checked
              if (onChange) {
                onChange(isChecked)
              }

              if (providedOnChange && isChecked && value) {
                providedOnChange(value)
              }
            }}
          />
          <span className="mcss-radio-label" data-disabled={disabled || undefined}>
            {children}
          </span>
        </label>
      )}
    </RadioGroupContext.Consumer>
  )
}

export default Radio

// packages/svelte/src/Radio.svelte
<script lang="ts">
import { createEventDispatcher, getContext } from 'svelte'

const dispatch = createEventDispatcher()
const radioGroupNameKey = 'minato-svelte:radio-group-name'

export let checked: boolean = false
export let disabled: boolean = false
export let name: string | undefined = undefined
export let group: number | undefined = undefined
export let value: number | undefined = undefined

$: checked = group !== undefined && group === value

const { getName, change } = getContext(radioGroupNameKey) ?? {}
$: computedName = getName ? getName() : name

const handleChange = () => {
  group = value
  dispatch('change', checked)
  change(value)
}
</script>

<label class="mcss-radio-container">
  <input
    class="mcss-radio"
    type="radio"
    {checked}
    {disabled}
    {value}
    name={computedName}
    on:change={handleChange}
  />
  <span class="mcss-radio-label" data-disabled={disabled ? true : undefined}><slot /></span>
</label>
