// packages/svelte-storybook/src/view/Button.svelte
<script lang="ts">
import { createEventDispatcher } from 'svelte'
import { Button } from '@minato-css/svelte'

export let label: string = ''
export let primary: boolean | null = null
export let danger: boolean | null = null
export let raise: boolean = true
export let disabled: boolean = false
export let type: 'button' | 'reset' | 'submit' = 'button'
</script>

<Button {primary} {danger} {raise} {disabled} {type} on:click>{label}</Button>

// packages/react/src/Button.tsx
import * as React from 'react'

export interface ButtonProps {
  primary?: boolean
  danger?: boolean
  raise?: boolean
  disabled?: boolean
  type?: 'button' | 'reset' | 'submit'
}

export const Button: React.FC<ButtonProps> = ({
  children,
  primary,
  danger,
  raise,
  type,
  disabled,
}) => (
  <button
    className="mcss-button"
    type={type ?? 'button'}
    disabled={disabled}
    data-primary={primary || undefined}
    data-danger={danger || undefined}
    data-no-raise={!raise || undefined}
  >
    {children}
  </button>
)

export default Button
